name: java-jooq-jpa

volumes:
  java-jooq-jpa-mariadb-data:

networks:
  java-jooq-jpa-net:

services:
  mariadb:
    image: 'mariadb:11.7-noble'
    container_name: 'java-jooq-jpa-mariadb'

    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect" ]
      interval: 10s
      timeout: 5s
      retries: 3

    restart: unless-stopped

    env_file:
      - ./.env

    volumes:
      - 'java-jooq-jpa-mariadb-data:/var/lib/mysq'

    environment:
      MARIADB_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'

      MARIADB_DATABASE: '${DATABASE_NAME}'
      MARIADB_USER: '${DATABASE_USER}'
      MARIADB_PASSWORD: '${DATABASE_PASSWORD}'

    ports:
      - '${DATABASE_PORT}:3306'

    networks:
      java-jooq-jpa-net: