name: java-jooq-jpa

volumes:
  java-jooq-jpa-postgres-data:

networks:
  java-jooq-jpa-net:

services:
  postgres:
    image: 'postgres:17.4-bookworm'
    container_name: 'java-jooq-jpa-postgres'

    restart: unless-stopped

    volumes:
      - 'java-jooq-jpa-postgres-data:/var/lib/postgresql/data/'

    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'

    ports:
      - '${DATABASE_PORT}:5432'

    networks:
      java-jooq-jpa-net: