--liquibase formatted sql
--changeset ManannikovAO:5351829382736
--comment: create h2 animals table

CREATE TABLE animals (
    animal_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    animal_russian_name VARCHAR NOT NULL UNIQUE,
    animal_latin_name VARCHAR NOT NULL UNIQUE,

    taxonomic_rank_id SMALLINT NOT NULL,

    animal_natural_habitat VARCHAR,

    animal_image_uri VARCHAR DEFAULT NULL,

    CONSTRAINT fk_animal_described_by_taxonomic_rank
        FOREIGN KEY (taxonomic_rank_id) REFERENCES taxonomic_ranks (taxonomic_rank_id)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT
);