server:
  port: '${JOOQ_JPA_PORT:8080}'
  address: '0.0.0.0'
  compression:
    enabled: true
  servlet:
    context-path: '/api'


spring:
  application:
    name: jooq-jpa

  liquibase:
    change-log: 'classpath:db/postgres-scripts/changelog-main.yaml'

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          batch_size: 32
          fetch_size: 32
        max_fetch_depth: 3
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: 'org.postgresql.Driver'

    url: '${DATABASE_URL}'
    username: postgres
    password: 124356

    hikari:
      auto-commit: true
      maximum-pool-size: 24