server:
  port: '${JOOQ_JPA_PORT:8080}'
  address: '0.0.0.0'
  compression:
    enabled: true
  servlet:
    context-path: '/api'


spring:
  application:
    name: jooq-jpa

  liquibase:
    change-log: 'classpath:db/postgres-scripts/changelog-main.yaml'

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 32
          fetch_size: 32
        max_fetch_depth: 3
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: validate
    generate-ddl: false

  datasource:
    driver-class-name: 'org.mariadb.jdbc.Driver'

    url: 'jdbc:mariadb://localhost:3307/testdb?useSSL=false'
    username: senioravanti
    password: 124356
    hikari:
      auto-commit: true
      maximum-pool-size: 24