CREATE TABLE taxonomic_rank_types
(
    taxonomic_rank_type_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomic_rank_type_name VARCHAR(24) NOT NULL UNIQUE
);

CREATE TABLE taxonomic_ranks
(
    taxonomic_rank_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    taxonomic_rank_parent_id INT DEFAULT NULL,
    taxonomic_rank_type      INT         NOT NULL,

    taxonomic_rank_name      VARCHAR(72) NOT NULL UNIQUE,

    CONSTRAINT fk_taxomic_rank_has_type
        FOREIGN KEY (taxonomic_rank_type) REFERENCES taxonomic_rank_types (taxonomic_rank_type_id)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,

    CONSTRAINT fk_taxomic_rank_level
        FOREIGN KEY (taxonomic_rank_parent_id) REFERENCES taxonomic_ranks (taxonomic_rank_id)
            ON DELETE CASCADE
            ON UPDATE RESTRICT
);