--liquibase formatted sql
--changeset ManannikovAO:5571239425456
--comment: create postgres animals table

CREATE TABLE animals (
    animal_id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    animal_russian_name varchar(32) NOT NULL UNIQUE,
    animal_latin_name varchar(64) NOT NULL UNIQUE,

    taxonomic_rank_id smallint NOT NULL,

    animal_natural_habitat varchar(2048),

    animal_image_uri varchar(128) DEFAULT NULL,

    CONSTRAINT fk_animal_described_by_taxonomic_rank
        FOREIGN KEY (taxonomic_rank_id) REFERENCES taxonomic_ranks (taxonomic_rank_id)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT
);