--liquibase formatted create postgres animals table
--changeset ManannikovAO:5571239425456
--comment: create postgres animals table

CREATE TABLE animals (
    animal_id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    animal_russian_name text NOT NULL UNIQUE,
    animal_latin_name text NOT NULL UNIQUE,

    taxonomic_rank_id smallint NOT NULL,

    animal_natural_habitat text NOT NULL,

    animal_image_uri text,

    CONSTRAINT fk_animal_described_by_taxonomic_rank
        FOREIGN KEY (taxonomic_rank_id) REFERENCES taxonomic_ranks (taxonomic_rank_id)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT
);